### DISCUSSION TITLE
Inference Graph supported by BentoML

### DISCUSSION THREAD

**Discussion by withsmilo** [bentoml/BentoML#1260] [Ideas]
Hi, BentoML team!
I'm trying to figure out how to implement an inference graph using the BentoML. We must be able to support real-time inference between several BentoServices already deployed in K8s in the form of **acyclic graph**. I think there are some following scenarios that can be considered when inferencing several models at the same time.

### 1. sequential inference : many one-model-in-one-BentoService
* This is really a bad design.
* supported by BentoML
<img width="474" alt="inference_graph_1" src="https://user-images.githubusercontent.com/3915543/99610621-8660a700-2a55-11eb-9958-653c5dd22aaa.png">

### 2. sequential inference : one multiple-models-in-one-BentoService
* supported by BentoML
  * https://github.com/bentoml/BentoML/discussions/928#discussioncomment-40962
  * https://docs.bentoml.org/en/latest/concepts.html#packaging-model-artifacts
<img width="562" alt="inference_graph_2" src="https://user-images.githubusercontent.com/3915543/99610709-aa23ed00-2a55-11eb-8867-180ae8b912d4.png">

### 3. sequential inference : many one-model-in-one-BentoService
* not yet supported by BentoML
<img width="770" alt="inference_graph_3" src="https://user-images.githubusercontent.com/3915543/99610740-b9a33600-2a55-11eb-829f-010993202fba.png">

### 4. parallel inference : one multiple-models-in-one-BentoService
* not yet supported by BentoML
  * User should implement directly some async operation between model1 and model2. This can sometimes be difficult for Data Scientist.
  * https://github.com/bentoml/BentoML/discussions/996#discussioncomment-52116
<img width="463" alt="inference_graph_4" src="https://user-images.githubusercontent.com/3915543/99610789-d2abe700-2a55-11eb-924d-54743e26416c.png">

### 5. parallel inference : many one-model-in-one-BentoService
* not yet supported by BentoML
  * User should implement directly some async operation between model2 and model3. This can sometimes be difficult for Data Scientist.
<img width="482" alt="inference_graph_5" src="https://user-images.githubusercontent.com/3915543/99610821-e3f4f380-2a55-11eb-91a7-8ba3933a6387.png">

### 6. graph definition : many one-model-in-one-BentoService
* not yet supported by BentoML
* This is just an idea. Here is a graph definition.
```yaml
inference_graph:
    endpoint: BentoService_A
    BentoService_A:
        - route: (BentoService_B, BentoService_E)
    BentoService_B:
        - model_1
        - route: (BentoService_C, BentoService_D)
    BentoService_C:
        - model_2
    BentoService_D:
        - model_3
    BentoService_E:
        - (model_4, model_5)
```
<img width="813" alt="inference_graph_6" src="https://user-images.githubusercontent.com/3915543/99610908-08e96680-2a56-11eb-8a0c-f5a90bcde60c.png">

Can BentoML cover all scenarios here in the future? I want to discuss with you how to implement all the scenarios here to provide a more convenient interface to users. Please let me know if there is anything I am missing. Any comments are welcome.
