### DISCUSSION TITLE
Deploying in Yatai using bentoml API

### DISCUSSION THREAD

**Discussion by mlopezfernandez** [bentoml/BentoML#2278] [Q&A]
I am delighted with how bentoml and yatai work. It has been easy to mount a small example locally and later deploy to AWS pointing to an S3. I have been able to deploy different models but all through the graphical interface. Would it be possible to do it using the bentoml API?

**Comment by yubozhao** [comment]
@mlopezfernandez Thank you for the encouraging words!

Right now, there are UI interface and kubectl available for deploying for the recent released 0.2.0 version (that added CRD support)

You can write k8s yaml file similar to this:
```yaml
apiVersion: serving.yatai.ai/v1alpha1
kind: BentoDeployment
metadata:
  name: demo
spec:
  bento_tag: iris_classifier:nxapohu4codzplg6
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 500m
```
and then call `kubectl apply -f` with this file.  Yatai will automatically deploy the deployment in that cluster
