### DISCUSSION TITLE
Setting the volume as a root user in Docker-Compose prevents Bentoml from accessing it

### DISCUSSION THREAD

**Discussion by aliebrahiiimi** [bentoml/BentoML#2354] [Q&A]
In target_plots, I want to write some output, but I get a ' Permission denied ' error, which I understand is because when I set the volume in docker-compose, it is set up as a root user, so Bentoml cannot access it. what is the best solution?

**I get the following in my Docker container:**
```
bentoml@5a09ef46cbb2:~$ ls -l
total 208
-rw-rw-r-- 1    1000    1000    737 Mar  7 07:59 bentoml_configuration.yml
drwxr-xr-x 1 bentoml bentoml   4096 Mar 14 06:02 bundle
-rw-rw-r-- 1    1000    1000  20373 Feb 28 08:17 common_stop_word.csv
-rw-rw-r-- 1    1000    1000    711 Mar 13 13:52 config.ini
drwxr-xr-x 2 bentoml bentoml   4096 Mar 14 06:02 logs
-rw-rw-r-- 1    1000    1000 160842 Jan  8 08:49 mofid_stop_word.csv
drwxr-xr-x 2 bentoml bentoml   4096 Mar 14 06:03 prometheus_multiproc_dir
drwxrwxr-x 2    1000    1000   4096 Mar 14 06:04 target_plots
```

**docker-compose.yml:**
```
version: '3.7'

services:

  bentoml:
    build: /home/ali/bentoml/repository/MLServices/1.0.2
    volumes:
      - ./config.ini:/home/bentoml/config.ini
      - ./mofid_stop_word.csv:/home/bentoml/mofid_stop_word.csv
      - ./common_stop_word.csv:/home/bentoml/common_stop_word.csv
      - ./bentoml_configuration.yml:/home/bentoml/bentoml_configuration.yml
      - ./target_plots:/home/bentoml/target_plots
    environment:
      - BENTOML_CONFIG=/home/bentoml/bentoml_configuration.yml
      - mofid_stop_word=/home/bentoml/mofid_stop_word.csv
      - common_stop_word=/home/bentoml/common_stop_word.csv
      - base_output_dir=/home/bentoml/target_plots
      - config_file=/home/bentoml/config.ini
    ports:
      - "5000:5000"
    deploy:
      mode: global
    restart: on-failure
```

**Comment by aarnphm** [comment]
Are you using bentoml docker container?

**Reply by aliebrahiiimi** [reply]
Yes, I changed it to the following and the errors stopped. Thanks for your reply @aarnphm .


docker-compose.yml
```
version: '3.7'

services:

  bentoml:
    user: root
    build: /home/ali/bentoml/repository/MLServices/1.0.2
    volumes:
      - ./config.ini:/home/bentoml/config.ini
      - ./mofid_stop_word.csv:/home/bentoml/mofid_stop_word.csv
      - ./common_stop_word.csv:/home/bentoml/common_stop_word.csv
      - ./bentoml_configuration.yml:/home/bentoml/bentoml_configuration.yml
      - ./target_plots:/home/bentoml/target_plots
    environment:
      - BENTOML_CONFIG=/home/bentoml/bentoml_configuration.yml
      - mofid_stop_word=/home/bentoml/mofid_stop_word.csv
      - common_stop_word=/home/bentoml/common_stop_word.csv
      - base_output_dir=/home/bentoml/target_plots
      - config_file=/home/bentoml/config.ini
    ports:
      - "5000:5000"
    deploy:
      mode: global
    restart: on-failure
```
