### DISCUSSION TITLE
How to correctly specify number of workers?

### DISCUSSION THREAD

**Discussion by volico** [bentoml/BentoML#3900] [Q&A]
How to specify number of workers? 
I tried using --api-workers in bentoml serve, but it seems that it doesn't make any difference.
Here is screenshot of my experiment with one of examples:

![BentoML_workers](https://github.com/bentoml/BentoML/assets/65400956/87965502-964f-4142-bb38-1e3956eae8a2)

I added print in serve.py and I can see multiple prints even if I specify number of api-workers=1. I observe this behaviour on other examples as welI. I also tried to set number of workers in configuration:

```
version: 1
api_server:
  workers: 1
runners:
  resources:
    cpu: 1
  workers_per_resource: 1
```

But it didn't help either. 

How should I correctly specify number of workers?
