### ISSUE TITLE
Use config in Dockerfile template

### ISSUE THREAD

**Issue by robbertvdg** [bentoml/BentoML#1338]
**Is your feature request related to a problem? Please describe.**
We want to host bento models on Kubernetes with a different port than the default and a custom number of gunicorn workers. The Dockerfile that BentoML creates has these variables hard-coded, therefore we cannot set them in our custom base Dockerfile. We are able to set them as variables in deployments, however we would like to minimize the deployment configuration to make it easier for our users.  

**Describe the solution you'd like**
The values in the [BentoML config](https://github.com/bentoml/BentoML/blob/master/bentoml/configuration/default_bentoml.cfg) can be used to specify the port, number of gunicorn workers (and possibly other settings) when generating this template, similarly to the used base image.

**Comment by parano** [comment]
Thanks for reporting this @robbertvdg, we are planning to add a way for the user to specify config values when creating a BentoML bundle, it is being tracked here: https://github.com/bentoml/BentoML/issues/1235

When deploying with Kubernetes, you can also pass the worker number argument directly, e.g.:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-bentoml
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 4
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: "bentoml-iris-classifier:1.0"
          ports:
            - name: http
              containerPort: 5000
              args: ["--workers", "5"]
```

As for the default port, I think in most cases, Kubernetes deployment doesn't really care about the port each container use, I could be wrong, could you tell me more about your use case and why you would need to specify a different port?
