### ISSUE TITLE
Allow ability to set number of workers when deploying to AWS ECS

### ISSUE THREAD

**Issue by sethfarns** [bentoml/BentoML#1358]
I am deploying my model to AWS ECS via BentoML, and have followed the [deployment guide](https://docs.bentoml.org/en/latest/deployment/aws_ecs.html) for this. The problem I have is that my model requires at least 4GB of memory to run, and I only want to run one worker at a time (for cost reasons). I see no way to specify the number of workers (`get_gunicorn_num_of_workers`), so BentoML calculates the number of workers based on CPU count. In order to get 4GB of memory using FARGATE, my minimum CPU size is 512, which BentoML is using to calculate 2 workers. Since I need at least 4GB of memory per worker, that means I need to set my memory size to 8GB, which gives me a far more costly ECS service than I would like. Would it be possible to allow us to set that `get_gunicorn_num_of_workers` value manually?

**Comment by yubozhao** [comment]
@sethfarns That's a good suggestion.  For AWS ECS deployment, you can do that via the `docker-compose.yml`.

Since AWS ECS uses docker-compose for deployment.  You can already customize the number of workers.  Here is how to set envvar in docker compose: https://docs.docker.com/compose/environment-variables/

For your cases, you can set the number of gunicorn workers with the envvar, `BENTOML__APISERVER__DEFAULT_GUNICORN_WORKERS_COUNT`

```
...
version: '3'
services:
  web:
    image: MY_BENTO_SERVICE_IMAGE
    environment:
      - BENTOML__APISERVER__DEFAULT_GUNICORN_WORKERS_COUNT=3
    ports:
      - "5000:5000"
    .....
```

Let me know if this solves your issue.  Happy to help
