### ISSUE TITLE
IrisClassifier model deployment on GKE failing due to permission error from creating /bentoml home directory

### ISSUE THREAD

**Issue by rileyhun** [bentoml/BentoML#1441]
I'm still having a lot of trouble getting GKE to run my model deployment without the pod crashing due to a permission error.

From checking the logs, I get this error:
`bentoml.exceptions.BentoMLConfigException: Error creating bentoml home directory '/bentoml': Permission denied`

**To Reproduce**

Run iris_classifier.py

```
import bentoml
from bentoml import env, artifacts, api, BentoService
from bentoml.adapters import DataframeInput
from bentoml.frameworks.sklearn import SklearnModelArtifact
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
import logging

bentoml.config().set('core', 'debug', 'true')
bentoml.configure_logging(logging.DEBUG)

def train():
    # Load training data
    iris = datasets.load_iris()
    X, y = iris.data, iris.target

    # Model Training
    model = RandomForestClassifier()
    model.fit(X, y)

    return model

@artifacts([SklearnModelArtifact('model')])
@env(docker_base_image="bentoml/model-server:0.8.5")
class IrisClassifier(BentoService):

    @api(input=DataframeInput(), batch=True)
    def predict(self, df):
        return self.artifacts.model.predict(df)

svc = IrisClassifier()
svc.pack('model', train())
svc.save()
```

Run these commands:
```
bentoml containerize IrisClassifier:latest -t iris_classifier:0.0.1
docker tag iris_classifier:0.0.1 gcr.io/project_id/iris_classifier:0.0.1
docker push gcr.io/project_id/iris_classifier:0.0.1
```

Apply seldon-kubernetes manifest
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: iris-model-bentoml
  namespace: seldon
spec:
  name: iris-model-bentoml
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - name: classifier
                image: gcr.io/project_id/iris_classifier:0.0.1
      graph:
        children: []
        endpoint:
          type: REST
        name: classifier
        type: MODEL
      name: example
      replicas: 1
```

**Environment:**
 - OS: MacOS
 - Python Version 3.8
 - BentoML Version 0.11.0

**Additional context**
https://bentoml.slack.com/archives/CKRANBHPH/p1612848455122900
