### ISSUE TITLE
Restructure the configuration of bentoml API server

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1489]
**Is your feature request related to a problem? Please describe.**
ref: https://github.com/bentoml/BentoML/pull/1476#discussion_r588818952

The current configuration structure for the API server:
```
api_server:
  port: 5000
  enable_microbatch: False
  run_with_ngrok: False
  enable_swagger: True
  enable_metrics: True
  enable_feedback: True
  max_request_size: 20971520
  workers: 1
  timeout: 60

marshal_server:
  port: Null  # default: api_server.port when enable_marshal=True
```

The batching server is seen as a standalone part, independent from the API server.
We can also see the batching layer as a consistent part of the bentoml API server.

So that bentoml could
- enable the marshal(batching) server by default, making the metrics endpoint non-blocking.
- pass requests by UNIX domain socket to achieve better performance.

**Describe the solution you'd like**

from @ssheng 
```
api_server:
  marshal(or batching_layer):
    enable: true
    connector:
      type: TCP/UDS
      host: 127.0.0.1 # TCP only
      port: Null # TCP only. Default: auto-detect
      path: /path/to/the/uds # UDS only.
  port: 5000
  run_with_ngrok: False
  enable_swagger: True
  enable_metrics: True
  enable_feedback: True
  max_request_size: 20971520
  workers: 1
  timeout: 60
```

This structure reflects the idea above.

**Describe alternatives you've considered**

**Additional context**
