### ISSUE TITLE
I changed my config of BentoML but still get Cors error from my Angular app

### ISSUE THREAD

**Issue by Ninhow** [bentoml/BentoML#1909]
**Describe the bug**
I created a config file and load BentoML with changed Cors config and still get cors error, i dont understand why.
`bento_bundle:
  deployment_version: Null
  default_docker_base_image: Null

bento_server:
  port: 5000
  ngrok:
    enabled: False
  workers: 1
  timeout: 60
  max_request_size: 20971520
  microbatch:
    workers: 1
    max_batch_size: Null
    max_latency: Null
  swagger:
    enabled: True
  metrics:
    enabled: True
    namespace: BENTOML
  feedback:
    enabled: True
  logging:
    level: INFO
  cors:
    enabled: True
    access_control_allow_origin: "*"
    access_control_allow_credentials: Null
    access_control_allow_methods: Null
    access_control_allow_headers: Null
    access_control_max_age: Null
    access_control_expose_headers: Null

logging:
  level: INFO
  console:
    enabled: True
  file:
    enabled: True
    directory: Null
  advanced:
    enabled: False
    config: Null

tracing:
  type: zipkin
  zipkin:
    url: Null
  jaeger:
    address: Null
    port: Null

adapters:
  image_input:
    default_extensions:
      - .jpg
      - .png
      - .jpeg
      - .tiff
      - .webp
      - .bmp

yatai:
  remote:
    url: Null
    access_token: Null
    access_token_header: access_token
    tls:
      root_ca_cert: Null
      client_certificate_file: Null
      client_key: Null
      client_cert: Null
  repository:
    type: file_system
    file_system:
      directory: Null
    s3:
      url: Null
      endpoint_url: Null
      signature_version: s3v4
      expiration: 3000
    gcs:
      url: Null
      expiration: 3000
  database:
    url: Null
  namespace: dev
  logging:
    path: Null
`
**Expected behavior**
I should not give cors error

**Environment:**
 - OS: [Win 10]
 - Python Version [3.8]
 - Angular is my frontend that I make requests to the API
both are in localhost

**Comment by parano** [comment]
Hi @Ninhow -for your frontend code to access the API server directly on a different domain, you will need to configure BentoServer's [CORS config](https://fetch.spec.whatwg.org/#http-cors-protocol), you can use the sample config below when running your BentoML server:

```
# bento_config.yaml
bento_server:
  cors:  
    enabled: True
    access_control_allow_origin: "*"
    access_control_allow_methods: ["GET", "OPTIONS", "POST", "HEAD", "PUT"]
    access_control_allow_credentials: True
    access_control_allow_headers: Null
    access_control_max_age: Null
    access_control_expose_headers: ["Content-Length"]
```

```
bentoml serve fraud_detector:latest --config ./bento_config.yaml
```
