### ISSUE TITLE
Inferring pip packages doesn't pick-up extra's

### ISSUE THREAD

**Issue by davidberenstein1957** [bentoml/BentoML#2037]
**Describe the bug**
I install spacy[cuda113] to be able to load their transformers model, however only spacy is added to the requirements file.

**To Reproduce**
Run a bento-packer that should infer spacy[cuda113] or any other package with extras.

**Expected behavior**
I expect the extras to be added to the packed model too.

**Environment:**
 - OS: [e.g. Windows 11]
 - Python Version [e.g. Python 3.8]
 - BentoML Version [e.g. BentoML-0.13.1]

**Additional context**
N.A.

**Comment by parano** [comment]
thanks for reporting the issue @davidberenstein1957! we will look into fixing this issue in 1.0 branch.

**Comment by parano** [comment]
Using PyPI package's extra dependency is supported in BentoML version 1.0 now. Note that BentoML 1.0 no longer support automatically inferring dependencies, instead it ask users to provide a list of required dependencies in your Bento project's `bentofile.yaml` file, e.g.:

```yaml
service: "iris_classifier:svc"
description: "file: ./readme.md"
labels:
  foo: bar
  team: abc
include:
- "*.py"
- "*.json"
exclude: 
- "*.pyc"
python:
  packages:
    - tensorflow
    - numpy
    - --index-url http://my.package.repo/simple/ SomePackage
    - --extra-index-url http://my.package.repo/simple SomePackage
    - -e ./my_py_lib
  index_url: http://<api token>:@mycompany.com/pypi/simple
  trusted_host: mycompany.com
  # index_url: null # means --no-index
  find_links:
    - file:///local/dir
    - thirdparth...
  extra_index_urls:
    - abc.com
  pip_args: "-- "
  wheels:
    - ./build/my_lib.whl
```
