### ISSUE TITLE
bentoml build  fails with AssertionError

### ISSUE THREAD

**Issue by jondoering** [bentoml/BentoML#2236]
**Describe the bug**

bentoml build  fails with AssertionError

**To Reproduce**
* build a model following https://docs.bentoml.org/en/latest/quickstart.html#getting-started-page
* tested locally with  bentoml serve ./run_model.py:svc --reload what worked
* try to docerize and build it with 'bentoml build' and it fails 
![image](https://user-images.githubusercontent.com/13738458/152075970-d6d42304-5aac-4b2a-b06a-cd92810207de.png)

**Expected behavior**

**Screenshots/Logs**

**Environment:**
- OS 
![image](https://user-images.githubusercontent.com/13738458/152076007-008544ae-30c3-4e90-8186-1419538f642d.png)

 - Python Version [e.g. Python 3.7.1]
 Python 3.8.8

 - BentoML Version [e.g. BentoML-0.8.6]
bentoml==1.0.0a3
My current requirement
[requirements.txt](https://github.com/bentoml/BentoML/files/7982827/requirements.txt)

**Additional context**

**Comment by parano** [comment]
Thanks for reporting the issue @jondoering - I'm able to reproduce this issue under `pip-22.0.2`, this is an issue from the dependency pip-tools and it's being fixed here: https://github.com/jazzband/pip-tools/pull/1559 

Unfortunately before that fix was released, you will need to downgrade pip to version 21.x in order to get it to work properly.

In the next release of BentoML, we are adding a `lock_packages` option to the bento build file, which will bypass the dependency locking step, e.g.:

```yaml
service: "iris_classifier:svc"
description: "file: ./readme.md"
labels:
  foo: bar
  team: abc
include:
- "*.py"
- "*.json"
exclude: 
- "*.pyc"
python:
  packages:
    - tensorflow
    - numpy
  lock_packages: false
```

I will keep you posted here when the next release is out in the next few days.
