### ISSUE TITLE
feat: Ability to force embedding a wheel file with local bentoml distrib

### ISSUE THREAD

**Issue by amelki** [bentoml/BentoML#2385]
**Is your feature request related to a problem? Please describe.**
Sometimes I may write a tentative fix or a tentative feature on my BentoML fork and use that fix in my company, waiting for the fixes/features to be submitted and accepted and released by the BentoML team.
The current solution is to pip install BentoML in _editable mode_. It works for me as a developer, but I want also let 
the data scientists in my team embed a given BentoML version, so I would like to be able to simply add the proper version to our requirements.txt.

**Describe the solution you'd like**
Add a BentoBuildConfig flag `python.local_dist` : when true, building a Bento will embed a wheel built from the local distribution.

**Comment by amelki** [comment]
Looking at the current code, seems difficult to do it without having bentoml installed in editable mode...
Closing it for now

**Comment by parano** [comment]
Hi @amelki, it's actually supported to include your local version of BentoML for deployment, because we need this for our testing. You can do it following these steps:

1. Install your local modified version of BentoML in edit mode, run this from your bentoml code repo: `pip install -e .`
2. Set an env var: `export BENTOML_BUNDLE_LOCAL_BUILD=True`
3. Build a new bento from your BentoML project: `bentoml build`

Now the new Bento built will include a whl of your local modified BentoML, and it will be installed in the containerize process.

**Comment by parano** [comment]
And for others who is just looking for including arbitrary wheel files in a Bento build, this is also supported. User can specify a list of wheel files to be included and install by default in a Bento, via the follow config in the `bentofile.yaml`:

```
# bentofile.yaml
service: "service:svc"
    description: "file: ./README.md"
    labels:
       owner: bentoml-team
       stage: demo
    include:
       - "*.py"
    python:
       packages:
          - scikit-learn
          - pandas
      wheels:
          - "./mylibs/*.whl"
```

**Comment by amelki** [comment]
Thanks @parano.
The local build was not the solution because I wanted to share a fix I integrated in my fork with some other folks in my company.
But here is how I finally addressed the problem:
```yaml
python:
    packages:
        - scikit-learn
        - pandas
        - git+https://github.com/amelki/BentoML.git@test/v1.0.0-a6-with-fix-for-2372
```

This works perfectly. If it's not yet somewhere in the documentation, I think it is a good candidate :)
