### ISSUE TITLE
Add build config to `bento.yaml` file in Bento

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2492]
Add build config options to bento.yaml file generated in Bento directory, e.g.:

```yaml
service: service:svc
name: iris_classifier
version: nvjtj7wwfgsafuqj
bentoml_version: 1.0.0a7.post49+g8353bb22
creation_time: '2022-05-17T21:36:36.436878+00:00'
labels:
  owner: bentoml-team
  project: gallery
models:
- tag: iris_clf:nb5vrfgwfgtjruqj
  module: bentoml.sklearn
  creation_time: '2022-05-17T21:36:27.656424+00:00'
runners:
- name: iris_clf
  runnable_type: SklearnRunnable
  models:
  - iris_clf:nb5vrfgwfgtjruqj
  resource_config:
    cpu: 10.0
    nvidia_gpu: 0.0
apis:
- name: classify
  input_type: NumpyNdarray
  output_type: NumpyNdarray

python:
	version: ..
	packages:
		...
conda:
	channels: ..
       packages: ..
docker:
	distro: debian
        cuda_version: ..
```
