### ISSUE TITLE
`index_url` isn't used to install dependencies in the `containerize` command

### ISSUE THREAD

**Issue by sbouchardet** [bentoml/BentoML#2552]
**Describe the bug**
Hello :wave: ,
I'm facing a problem in the `bentoml containerize sknn:xu7rnbhfvw2d7mi2` command in the `Installing pip packages from 'requirements.txt'` stage when it tries to install a package from an internal registry. 

**To Reproduce**
My `bentofile.yaml` is something like:
```yaml
service: "service:svc"
labels:
   owner: recommendation-team
   stage: dev
include:
- "service.py"
python:
  requirements_txt: "./requirements.txt"
  index_url: "https://<other api token>:@my.mirror.com/pypi/simple"
```
If there is a dependency listed in `requirements.txt` that exists only in `my.mirror.com`, the package can't be found. In the below log, the dependency is the `sknn` package.

```
#0 5.644 ERROR: Could not find a version that satisfies the requirement sknn==0.1.1 (from versions: none)
#0 5.644 ERROR: No matching distribution found for sknn==0.1.1
...
error: failed to solve: executor failed running [/bin/bash -eo pipefail -c bash <<EOF
if [ -f /home/bentoml/bento/env/python/pip_args.txt ]; then
  EXTRA_PIP_INSTALL_ARGS=$(cat /home/bentoml/bento/env/python/pip_args.txt)
fi
if [ -f /home/bentoml/bento/env/python/requirements.lock.txt ]; then
  echo "Installing pip packages from 'requirements.lock.txt'.."
  pip install -r /home/bentoml/bento/env/python/requirements.lock.txt -U $EXTRA_PIP_INSTALL_ARGS
else
  if [ -f /home/bentoml/bento/env/python/requirements.txt ]; then
    echo "Installing pip packages from 'requirements.txt'.."
    pip install -r /home/bentoml/bento/env/python/requirements.txt $EXTRA_PIP_INSTALL_ARGS
  fi
fi
```

However, if I get the `pip_args.txt` content (from  `~/bentoml/bentos/sknn/xu7rnbhfvw2d7mi2/env/python/pip_args.txt`), and replace it in the `EXTRA_PIP_INSTALL_ARGS` usages (in `~/bentoml/bentos/sknn/xu7rnbhfvw2d7mi2/env/docker/Dockerfile), it works.

**Screenshots/Logs**
I add some `echo`s in the `Dockerfile` during my investigation. 
![image](https://user-images.githubusercontent.com/10326691/172202767-6a14e9ee-b043-4e3d-9655-972f98166ab4.png)
and
![image](https://user-images.githubusercontent.com/10326691/172203740-12ed5f4a-80a7-4ea5-bc8b-769e9bb68d4c.png)

I hope it helps :blush: 

**Environment:**
 - OS: Ubuntu 20.04
 - Python 3.8.10
 - bentoml, version 1.0.0rc0
 - Docker version 20.10.14, build a224086

**Comment by aarnphm** [comment]
Hi @sbouchardet, Thanks for reporting the bug. I will put up the fix right away

**Comment by aarnphm** [comment]
@sbouchardet can you try putting your index url to `extra_index_url` instead?

**Comment by sbouchardet** [comment]
Btw, I'm interesting to contribute to this project. Could you show me a good first issue to solve?

**Comment by aarnphm** [comment]
Oh your index url got double quote
it should be 
```
python:
  extra_index_url:
    - "https://<other api token>:@my.mirror.com/pypi/simple"
 ```

**Comment by aarnphm** [comment]
on my end I tried this
```yaml
# bentofile.yaml
service: "service.py:svc"
labels:
  owner: bentoml-team
  project: gallery
include:
- "*.py"
exclude:
- tests
- "*.go"
python:
  lock_packages: True
  requirements_txt: "./extra-requirements.txt"
  extra_index_url: 
  - "https://test.pypi.org/simple/"
```
