### ISSUE TITLE
question: Local Bento Deployment has different behavior from UI deployment

### ISSUE THREAD

**Issue by gaspard-met** [bentoml/BentoML#2569]
FYI @timliubentoml , we discussed this on Slack and I found it easier to fully document it here

**Describe the bug**
For a given Bento, and with the same arguments, the local `kubectl apply` command creates a deployment with only a `Cluster internal URL` and no URL accessible from outside the cluster

Setup: 
- `bentoml==1.0.0a7`
- minikube
- `yatai-chart==v0.3.2`

**To Reproduce**

1. Common ground:
- I train a toy example model locally
- I build the bento locally
- I push the latest tag (`snsldmxhacgjkaav`) to Yatai 
- Both models and bento push succeed on Yatai

2. Local deployment:
- My `deployment.yaml` file: 
```
apiVersion: serving.yatai.ai/v1alpha2
kind: BentoDeployment
metadata:
  name: regression
spec:
  bento_tag: elon_worth:snsldmxhacgjkaav
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 500m
```
- The command: 
`kubectl apply -f path_to_config/deployment.yaml `

**Screenshots/Logs**

What happens in Yatai after local command: 
- Deployment panel
There isn't an accessible URL to access the swagger
![image](https://user-images.githubusercontent.com/78359781/172576519-8f20734c-30c9-4173-aa50-11602c533153.png)

Note: it's not very easy to copy/paste the logs from Yatai UI (see my issue on the topic https://github.com/bentoml/Yatai/issues/249)
I didn't manage to get all the logs, is there another place where I could see them ? Didn't find them on k9s

3. Yatai UI deployment
- From the deployment panel
I clicked "Create", gave a name and selected the latest tag. Nothing else

- Deployment panel
Here, there is an accessible URL with the swagger from the get-go
![image](https://user-images.githubusercontent.com/78359781/172584232-e7c07a04-3e21-4fef-8a4a-a6b01c761bba.png)

Is it possible on my side to adapt the `kubectl` command or the deployment config to be able to access the SwaggerUI ? 

thanks !

**Comment by parano** [comment]
Hi @gaspard-met - thank you for the feedback! this is expected behavior but we should definitely improve the documentation for it. Basically the default value for `ingress` is True when creating from the UI, you can see a toggle enabled by default in the deployment creation UI. When creating a deployment from kubectl, the user needs to explicitly set the value to true. E.g.:

```yaml
# my_deployment.yaml
apiVersion: serving.yatai.ai/v1alpha2
kind: BentoDeployment
metadata:
  name: demo
spec:
  bento_tag: iris_classifier:3oevmqfvnkvwvuqj
  ingress:
    enabled: true
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 500m
```

see https://github.com/bentoml/Yatai/blob/d484b483d7a6db3aa1e39864b1183895807717ab/docs/bentodeployment_crd.md for more details
