### ISSUE TITLE
build_config(env): not escape space accordingly

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#2593]
**Describe the bug**

Currently if users pass in space environment variables `BuildConfig` wouldn't be able to process it accordingly
```yaml
service: "service.py:svc"
env:
  my space: 1
  ENV: hello world
``` 

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**
