### ISSUE TITLE
bug: Bento keyword "bento_server" is forbidden in bentofile.yaml config.

### ISSUE THREAD

**Issue by muneebable** [bentoml/BentoML#3134]
### Describe the bug

Version = 1.0.7
In the old version and in documentation, people used that keyword in bentoml.ymal file. But now It is not recoginizable anymore. 

We tried to add:
```
bento_server:
  cors:  
    enabled: True
    access_control_allow_origin: "*"
    access_control_allow_methods: ["GET", "OPTIONS", "POST", "HEAD", "PUT"]
    access_control_allow_credentials: True
    access_control_allow_headers: Null
    access_control_max_age: Null
    access_control_expose_headers: ["Content-Length"]

```

But that doesn't work. and we got the error as displayed in the image.

![image](https://user-images.githubusercontent.com/3126387/197501721-9406c440-64b5-4ddf-be9a-283c7ee2b9b7.png)

### Environment

bentoml: 1.0.7
python: 3.9
platform: Ubuntu 20.04.5 LTS
