### ISSUE TITLE
bug: "bentoml build" command takes too long time but there is no additional message with "--verbose" tag.

### ISSUE THREAD

**Issue by seyong92** [bentoml/BentoML#3235]
### Describe the bug

In "bentofile.yaml", we only include "*.py" file and some text files, but it takes a too long time to build bento.

It takes more than 1 hour for building bentos, and the created bento is just around 50 MB.

When I use "--verbose" tag when using "bento build", it does not return anything, so I cannot know the reason.

### To reproduce

I just share the "bentofile.yaml" file of my project.

```yaml
service: "bentoml_service:svc"
labels:
  owner: our-team
  stage: dev
include:
  - "*.py"
  - "*.csv"
exclude:
  - "log_save/"
  - "model_save/"
python:
  requirements_txt: "./requirements.txt"
docker:
  distro: debian
  python_version: "3.9.13"
  cuda_version: "11.6.2"
  system_packages:
    - libsndfile-dev
    - ffmpeg
```

### Environment

bentoml: 1.0.10
python: 3.9.13
