### ISSUE TITLE
bug: `PERMISSION_DENIED` when trying to send OpenTelemetry trace data from a bento service to NewRelic

### ISSUE THREAD

**Issue by phitoduck** [bentoml/BentoML#3740]
### Describe the bug

Hi there, I'm trying to send trace data generated by my BentoML application to NewRelic.

Actually, I'm trying to get metrics *and* traces into NewRelic, but I think I may have solved metrics, and so I think this issue should be restricted to traces.

Basically: when I try to send my traces to NewRelic from my BentoML service, I get a `PERMISSION_DENIED` error from within my BentoML app.

Some resources:

- There's a [thread in slack](https://bentoml.slack.com/archives/CKRANBHPH/p1679082751461319?thread_ts=1679008498.103059&cid=CKRANBHPH) documenting my approach. @ssheng is on the thread 😁. This issue is essentially a condensed version of the thread.
- I made a minimal example and instructions for how to run it on GitHub [in this repository](https://github.com/phitoduck/bentoml-opentelemetry-newrelic).

I opened up a support case with NewRelic, including my minimal example. They ran it locally and were able to reproduce my error when using their own token. 👍

They sent me this:

> Hello,
>
> Thanks for your patience.
>
> I went over this with our engineers within the OTEL space and unfortunately they are not familiar enough with the BentoML product to advise on how to resolve this. 
>
> The issue doesn't appear to be related to the license key being invalid, since it was failing with the permission denied message for me as well. The team suggested filing an issue with BentoML as the next step, and letting them know that there is an issue with sending data when authentication is required. 
>
> I'm sorry I don't have better news.

Copy/pasting from the thread:

Here's my `docker-compose.yaml` file. Note that it relies on a `.env` file with the contents `NEW_RELIC_LICENSE_KEY=<my key>`

```yaml
version: "3.8"

services:
  bento-service:
    image: dummy-service:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/home/bentoml/bento/src/
      - ./bentoml_configuration.yaml:/home/bentoml/bentoml_configuration.yaml
    command: serve --port 3000 --debug # have tried with --production as well
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net/
      # I've tried enabling/disabling this
      OTEL_EXPORTER_OTLP_HEADERS: api-key=${NEW_RELIC_LICENSE_KEY},service.name=opentelemetry-bento-svc
      BENTO_CONFIG: /home/bentoml/bentoml_configuration.yaml
    env_file:
      - .env
```

And here's my `bentoml_configuration.yaml`

```yaml
version: 1
api_server:
  tracing:
    enabled: true
    exporter_type: otlp
    sample_rate: 1.0
    otlp:
      protocol: grpc
      endpoint: https://otlp.nr-data.net/
      grpc:
        insecure: false
        headers:
          - ["grpc-encoding", "gzip"]
          - ["api-key", "${NEW_RELIC_LICENSE_KEY}"]
          - ["service.name", "opentelemetry-bento-svc"]
```

But when I run `docker-compose up`, `bentoml` gives me this warning

When I try to push traces to NewRelic, I get

```log
Failed to export traces, error code: StatusCode.PERMISSION_DENIED
```

And when I remove the API key altogether, I get

```log
Failed to export traces, error code: StatusCode.UNAUTHENTICATED
```

### To reproduce

Covered in the description 👍

### Expected behavior

We should not see a permission error, but instead should have the traces successfully appear in the NewRelic console. 

The intended result of this would be twofold:

1. Be able to trace requests that span multiple REST APIs where all REST APIs are instrumented with OpenTelemetry and some of those REST APIs are BentoML services
2. Have a trace ID placed in the return header of all requests to BentoML services so we can look up the logs that were generated while that request was being handled

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=/home/bentoml/bentoml_configuration.yaml
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.0.16
`python`: 3.10.10
`platform`: Linux-5.15.49-linuxkit-x86_64-with-glibc2.31
`uid_gid`: 1034:1034
<details><summary><code>pip_packages</code></summary>

<br>

```
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
appdirs==1.4.4
asgiref==3.6.0
async-timeout==4.0.2
attrs==22.2.0
backoff==2.2.1
bentoml==1.0.16
build==0.10.0
cattrs==22.2.0
certifi==2022.12.7
charset-normalizer==3.1.0
circus==0.18.0
click==8.1.3
click-option-group==0.5.5
cloudpickle==2.2.1
contextlib2==21.6.0
deepmerge==1.1.0
Deprecated==1.2.13
exceptiongroup==1.1.1
frozenlist==1.3.3
fs==2.4.16
googleapis-common-protos==1.58.0
grpcio==1.51.3
h11==0.14.0
idna==3.4
Jinja2==3.1.2
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mdurl==0.1.2
multidict==6.0.4
numpy==1.24.2
opentelemetry-api==1.14.0
opentelemetry-exporter-otlp==1.14.0
opentelemetry-exporter-otlp-proto-grpc==1.14.0
opentelemetry-exporter-otlp-proto-http==1.14.0
opentelemetry-instrumentation==0.35b0
opentelemetry-instrumentation-aiohttp-client==0.35b0
opentelemetry-instrumentation-asgi==0.35b0
opentelemetry-proto==1.14.0
opentelemetry-sdk==1.14.0
opentelemetry-semantic-conventions==0.35b0
opentelemetry-util-http==0.35b0
packaging==23.0
pathspec==0.11.1
pip-requirements-parser==32.0.1
pip-tools==6.12.3
prometheus-client==0.16.0
protobuf==3.20.3
psutil==5.9.4
pydantic==1.10.6
Pygments==2.14.0
pynvml==11.5.0
pyparsing==3.0.9
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
PyYAML==6.0
pyzmq==25.0.2
requests==2.28.2
rich==13.3.2
schema==0.7.5
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.25.0
tomli==2.0.1
tornado==6.2
typing_extensions==4.5.0
urllib3==1.26.15
uvicorn==0.21.1
watchfiles==0.18.1
wrapt==1.15.0
yarl==1.8.2
```

</details>
