### ISSUE TITLE
bug: support environment variables for python build extra_index_url

### ISSUE THREAD

**Issue by nadworny** [bentoml/BentoML#3755]
### Describe the bug

Build bento using an extra index url that contains an environment variable. Instead, the following error happens:
```
#12 0.282 Installing pip packages from 'requirements.txt'..
#12 0.284 + pip3 install -r /home/bentoml/bento/env/python/requirements.txt --no-warn-script-location --extra-index-url 'https://$PYPI_TOKEN:@pkgs.dev.azure.com/xxx/_packaging/xxx/pypi/simple'
#12 9.132 Looking in indexes: https://pypi.org/simple, https://%24PYPI_TOKEN:****@pkgs.dev.azure.com/xxx/_packaging/xxx/pypi/simple
#12 10.00 WARNING: 401 Error, Credentials not correct for https://pkgs.dev.azure.com/xxx/_packaging/xxx/pypi/simple/mlflow/
```

### To reproduce

1. Have the following `bentofile.yaml`
```yaml
service: "sevice.Model:svc"
python:
  requirements_txt: "$BENTOML_MLFLOW_MODEL_PATH/mlflow_model/requirements.txt"
  extra_index_url:
  - "https://$PYPI_TOKEN:@pkgs.dev.azure.com/xxx/_packaging/xxx/pypi/simple"
```
2. Export the token `export PYPI_TOKEN=abc`
3. Export model `export BENTOML_MLFLOW_MODEL_PATH=$(bentoml models get demo:latest -o path)`
4. Run
```console
bentoml build
bentoml containerize demo_service:latest 
```

### Expected behavior

Requirements are installed successfully and bentoml image is created.

### Environment

bentoml, version 1.0.18
Python 3.8.12 (default, Mar 16 2023, 16:38:07) 
m1 macos
