### ISSUE TITLE
feature: Support for poetry managed dependency file in bentofile.yaml

### ISSUE THREAD

**Issue by rajatm91** [bentoml/BentoML#4012]
### Feature request

Hi team, we are using poetry as our dependency manager, and are trying to build a container. our bentofile.yaml looks like this:
```
service: "main:app"
labels:
  owner: XYZ
  stage: dev
exclude:
  - "tests/"
python:
  requirements_txt: "requirements.txt"
  trusted_host:
    - "pypi.python.org"
docker:
  dockerfile_template: ./Dockerfile.template
  ```
  
  Can we use `pyproject.toml` or `poetry.lock` instead of requirements.txt to provide the dependencies?

### Motivation

This feature will help us to use single source of truth for managing dependencies. Currently, there is an extra step to create a `requirements.txt file` from the `pyproject.toml` file using `poetry export ..` command.
