### ISSUE TITLE
feature:  `index_url` from bentofile.yaml not reflected in generated Dockerfile

### ISSUE THREAD

**Issue by darlingbud** [bentoml/BentoML#5373]
### Feature request

I followed the documentation to configure the `bentofile.yaml` and added the `index_url` parameter under the `python` section. However, this configuration does not seem to be reflected in the generated Dockerfile.

The `--index-url` argument is missing during package installation in the Docker build stage. As a result, dependencies are installed from the default PyPI source instead of the specified mirror.

this is bentofile.yaml
```
service: "service:svc"
description :
  This is an inline description for the Service. BentoML is awesome!

include:
  - "*.py"

python:
  requirements_txt: './requirements.txt'
  index_url: "https://pypi.tuna.tsinghua.edu.cn/simple"
  # lock_packages: false
  
docker:
  distro: debian
  python_version: "3.12.3"
  
```
and the dockerfile part like this
```
# install python packages
RUN uv --directory ./env/python/ pip install -r requirements.txt
```

**Comment by frostming** [comment]
It should be in the final `requirements.txt`, please check it.

**Comment by darlingbud** [comment]
> It should be in the final `requirements.txt`, please check it.

Thank you !, It's in the final requirements.txt.
but I also have  problems  , I have a question regarding the Dockerfile used in BentoML's containerization process.

In the Dockerfile, there is a step like this:
`RUN command -v uv >/dev/null || pip install uv.`

Due to some network restrictions, I need the pip install command to use a custom PyPI mirror like the --index-url option. So I tried modifying the Dockerfile located at `/bentoml/bentos/.../Dockerfile`, and added an environment variable like this:
`ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple` .

However, when I tested the bentoml containerize command, it didn't seem to take effect. From what I observed, it looks like BentoML generates a temporary Dockerfile in the` /tmp `directory during the build process, which may not be the same as the Dockerfile under `/bentoml/bentos`.

So my questions are:

Is it possible to customize or override the Dockerfile used during the bentoml containerize step?
How can I ensure that all pip install commands (including those executed by tools like uv) respect a specified --index-url?
Can setting ENV PIP_INDEX_URL=... in the Dockerfile affect the entire build context?
Any help or guidance would be greatly appreciated!

**Comment by frostming** [comment]
As the env vars are set at an early stage: https://github.com/bentoml/BentoML/blob/6eea834188f4452a127332097339df84603b546a/src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2#L52-L56

You can set env `PIP_INDEX_URL` to do that:

```yaml
envs:
  - name: PIP_INDEX_URL
    value: https://mirrors.aliyun.com/pypi/simple
```
