### ISSUE TITLE
YataiService's Docker doesn't include psycog

### ISSUE THREAD

**Issue by fernandocamargoti** [bentoml/BentoML#643]
**Describe the bug**
According to the docs, I could use YaitaiService's Docker with another database as follows:

```
docker run -p 3000:3000 -p 50051:50051 \
    -e AWS_SECRET_ACCESS_KEY=... -e AWS_ACCESS_KEY_ID=...  \
    bentoml/yatai-service:0.7.2 \
    --db-url postgresql://scott:tiger@localhost:5432/bentomldb \
    --repo-base-url s3://my-bentoml-repo/
```

But we get a "ModuleNotFoundError: No module named 'psycopg2'" if we try it.

**To Reproduce**

The following docker-compose.yml is the easiest way to reproduce:
```
version: '3'

services:
  yatai-service:
    build: yatai-service
    restart: unless-stopped
    command: "--db-url=postgres://postgres@yatai-db:5432/bentomldb --repo-base-url=/bentoml/repository"
    volumes:
      - ./data/yatai/repository:/bentoml/repository
    depends_on:
      - yatai-db
    networks:
      - yatai
  yatai-db:
    image: library/postgres:latest
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=bentomldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/yatai/db:/var/lib/postgresql/data
    networks:
      - yatai
networks:
  yatai: {}
```

**Expected behavior**
YataiService connecting to the database.

**Environment:**
 - OS: Manjaro 20.0
 - YataiService Version: 0.7.5

**Comment by parano** [comment]
hi @fernandocamargoti, this issue has been fixed and we are re-releasing the docker images from 0.7.0-0.7.5, I've verified with the following docker-compose.yml file and the server starts up properly now:

```
version: '3'

services:
  yatai-service:
    restart: unless-stopped
    image: bentoml/yatai-service:0.7.5
    command: "--db-url=postgres://postgres@yatai-db:5432/bentomldb --repo-base-url=/bentoml/repository"
    volumes:
      - ./data/yatai/repository:/bentoml/repository
    depends_on:
      - yatai-db
    networks:
      - yatai
  yatai-db:
    image: library/postgres:latest
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=bentomldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/yatai/db:/var/lib/postgresql/data
    networks:
      - yatai
networks:
  yatai: {}
```
