### ISSUE TITLE
YataiService server start should check and wait for db to be ready

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#647]
**Is your feature request related to a problem? Please describe.**
When launching YataiService with database instance together via docker-compose(see example here: https://github.com/bentoml/BentoML/issues/643) or Kubernetes, the yatai-service will fail to start due to the db instance not being ready.

```
version: '3'

services:
  yatai-service:
    restart: unless-stopped
    image: bentoml/yatai-service:0.7.5
    command: "--db-url=postgres://postgres@yatai-db:5432/bentomldb --repo-base-url=/bentoml/repository"
    volumes:
      - ./data/yatai/repository:/bentoml/repository
    depends_on:
      - yatai-db
    networks:
      - yatai
  yatai-db:
    image: library/postgres:latest
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=bentomldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/yatai/db:/var/lib/postgresql/data
    networks:
      - yatai
networks:
  yatai: {}
```

**Describe the solution you'd like**
When the db is not ready for connection, wait and re-try with a max-time-out option

**Describe alternatives you've considered**
Support something like https://github.com/Eficode/wait-for or https://github.com/vishnubob/wait-for-it on yatai-service docker container and allow the user to specify the wait parameter

**Additional context**
none
